import Base
import ../laws/attachview.bend as Laws

def Laws.av_imagem_tag():
  {==}

def Laws.av_imagem_classe():
  {==}

def Laws.av_imagem_key():
  {==}

def Laws.av_imagem_dois_filhos():
  {==}

def Laws.av_imagem_tag_img():
  {==}

def Laws.av_imagem_src():
  {==}

def Laws.av_imagem_alt():
  {==}

def Laws.av_imagem_sem_lazy():
  {==}

def Laws.av_imagem_lazy_loading():
  {==}

def Laws.av_imagem_lazy_decoding():
  {==}

def Laws.av_imagem_alt_lazy():
  {==}

def Laws.av_imagem_botao_tag():
  {==}

def Laws.av_imagem_botao_classe():
  {==}

def Laws.av_imagem_botao_tipo():
  {==}

def Laws.av_imagem_botao_rotulo():
  {==}

def Laws.av_imagem_botao_title():
  {==}

def Laws.av_imagem_botao_sem_title():
  {==}

def Laws.av_imagem_botao_evento():
  {==}

def Laws.av_imagem_botao_texto():
  {==}

def Laws.av_arquivo_classe():
  {==}

def Laws.av_arquivo_key():
  {==}

def Laws.av_arquivo_dois_filhos():
  {==}

def Laws.av_arquivo_rotulo():
  {==}

def Laws.av_arquivo_texto():
  {==}

def Laws.av_arquivo_botao_rotulo():
  {==}

def Laws.av_arquivo_botao_title():
  {==}

def Laws.av_arquivo_botao_evento():
  {==}

def Laws.av_lista_uma_imagem():
  {==}

def Laws.av_lista_imagem_arquivo():
  {==}

def Laws.av_lista_ordem():
  {==}

def Laws.av_lista_primeira_key():
  {==}

def Laws.av_lista_duas_imagens():
  {==}

def Laws.av_lista_vazia():
  {==}

def Laws.av_chip_id():
  {==}

def Laws.av_chip_classe():
  {==}

def Laws.av_chip_tres_filhos():
  {==}

def Laws.av_chip_rotulo():
  {==}

def Laws.av_chip_texto():
  {==}

def Laws.av_chip_title():
  {==}

def Laws.av_chip_corta():
  {==}

def Laws.av_chip_given_longo_acrescenta():
  {==}

def Laws.av_chip_curto():
  {==}

def Laws.av_chip_pred_curto():
  {==}

def Laws.av_chip_pred_no_teto():
  {==}

def Laws.av_chip_pred_acima():
  {==}

def Laws.av_chip_auto_corta():
  {==}

def Laws.av_chip_view_given_title():
  {==}

def Laws.av_chip_view_given_texto():
  {==}

def Laws.av_chip_view_given_curto():
  {==}

def Laws.av_chip_visivel_corta():
  {==}

def Laws.av_chip_visivel_curto():
  {==}

def Laws.av_chip_botao_classe():
  {==}

def Laws.av_chip_botao_rotulo():
  {==}

def Laws.av_chip_botao_title():
  {==}

def Laws.av_chip_botao_evento():
  {==}

def Laws.av_chip_botao_texto():
  {==}
