import Base
import ../laws/comfortview.bend as Laws

def Laws.comfort_hysteresis_liga():
  {==}

def Laws.comfort_hysteresis_espera():
  {==}

def Laws.comfort_hysteresis_mantem():
  {==}

def Laws.comfort_hysteresis_desliga():
  {==}

def Laws.comfort_fades():
  {==}

def Laws.comfort_density_id():
  {==}

def Laws.comfort_density_event():
  {==}

def Laws.comfort_reading_id():
  {==}

def Laws.comfort_reading_options():
  {==}

def Laws.comfort_jump_hidden():
  {==}

def Laws.comfort_jump_visible():
  {==}

def Laws.comfort_jump_label():
  {==}

def Laws.comfort_jump_icon():
  {==}
