import Base
import ../laws/paletteview.bend as Laws

def Laws.pv_segmento_marcado():
  {==}

def Laws.pv_segmento_texto():
  {==}

def Laws.pv_conta_itens():
  {==}

def Laws.pv_item_ativo():
  {==}

def Laws.pv_item_inativo():
  {==}

def Laws.pv_item_id():
  {==}

def Laws.pv_mark_filho_texto():
  {==}

def Laws.pv_check_substitui_kbd():
  {==}

def Laws.pv_kbd_sem_check():
  {==}

def Laws.pv_quando_opcional():
  {==}

def Laws.pv_secao_vazia_some():
  {==}

def Laws.pv_lista_vazia():
  {==}

def Laws.pv_backdrop():
  {==}

def Laws.pv_lista_id():
  {==}

def Laws.pv_input_ativo():
  {==}

def Laws.pv_input_sem_ativo():
  {==}

def Laws.pv_dica():
  {==}
